-- public."user" definition

-- Drop table

-- DROP TABLE public."user";

CREATE TABLE public."user" (
	is_removed bool NOT NULL,
	created_at timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NULL,
	full_name varchar(255) NULL,
	"password" varchar(255) NULL,
	phone varchar(255) NULL,
	CONSTRAINT user_pkey PRIMARY KEY (id)
);


-- public.account definition

-- Drop table

-- DROP TABLE public.account;

CREATE TABLE public.account (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	is_removed bool NOT NULL,
	balance numeric(38, 2) NULL,
	currency varchar(255) NULL,
	"name" varchar(255) NULL,
	"type" varchar(255) NULL,
	user_id int8 NULL,
	total_balance numeric(38, 2) NULL,
	CONSTRAINT account_currency_check CHECK (((currency)::text = ANY ((ARRAY['TL'::character varying, 'USD'::character varying, 'EUR'::character varying])::text[]))),
	CONSTRAINT account_pkey PRIMARY KEY (id),
	CONSTRAINT account_type_check CHECK (((type)::text = ANY ((ARRAY['CREDIT_CARD'::character varying, 'CASH'::character varying, 'BANK'::character varying])::text[]))),
	CONSTRAINT fklpehafsh6t7ka32286sp7ipi7 FOREIGN KEY (user_id) REFERENCES public."user"(id)
);


-- public.contact definition

-- Drop table

-- DROP TABLE public.contact;

CREATE TABLE public.contact (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	is_removed bool NOT NULL,
	full_name varchar(255) NULL,
	note text NULL,
	user_id int8 NULL,
	CONSTRAINT contact_pkey PRIMARY KEY (id),
	CONSTRAINT fk6bvjsduardbg5jq01n6wxiui2 FOREIGN KEY (user_id) REFERENCES public."user"(id)
);


-- public."transaction" definition

-- Drop table

-- DROP TABLE public."transaction";

CREATE TABLE public."transaction" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	is_removed bool NOT NULL,
	description varchar(255) NULL,
	paid_amount numeric(38, 2) NULL,
	status varchar(255) NULL,
	total_amount numeric(38, 2) NULL,
	total_installment int4 NULL,
	"type" varchar(255) NULL,
	account_id int8 NULL,
	contact_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT transaction_pkey PRIMARY KEY (id),
	CONSTRAINT transaction_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PARTIAL'::character varying, 'PAID'::character varying])::text[]))),
	CONSTRAINT transaction_type_check CHECK (((type)::text = ANY ((ARRAY['DEBT'::character varying, 'CREDIT'::character varying, 'PAYMENT'::character varying, 'COLLECTION'::character varying])::text[]))),
	CONSTRAINT fk6g20fcr3bhr6bihgy24rq1r1b FOREIGN KEY (account_id) REFERENCES public.account(id),
	CONSTRAINT fk82li5mb1m8nui9y7h5ivncoft FOREIGN KEY (contact_id) REFERENCES public.contact(id),
	CONSTRAINT fk8vb9nyxwuxe10hhd3bkr67h3n FOREIGN KEY (user_id) REFERENCES public."user"(id)
);


-- public.installment definition

-- Drop table

-- DROP TABLE public.installment;

CREATE TABLE public.installment (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NULL,
	is_removed bool NOT NULL,
	amount numeric(38, 2) NULL,
	installment_number int4 NULL,
	is_paid bool NOT NULL,
	paid_date timestamp(6) NULL,
	transaction_id int8 NULL,
	CONSTRAINT installment_pkey PRIMARY KEY (id),
	CONSTRAINT fkq04sunhaybag8qcjer2nmbhlh FOREIGN KEY (transaction_id) REFERENCES public."transaction"(id)
);